name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    PROJECT_NAME: ProCardTheme
    # GitHub Packages Feed settings
    GITHUB_FEED: https://nuget.pkg.github.com/KshitizGIT/
    GITHUB_USER: KshitizGIT
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Official NuGet Feed settings
    NUGET_FEED: https://api.nuget.org/v3/index.json
    NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./src/ProCardTheme
      run: dotnet restore
    - name: Build
      working-directory: ./src/ProCardTheme
      run: dotnet build -c Release --no-restore
    - name: Test
      working-directory: ./src/ProCardTheme
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack -c Release -v normal --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID-rc2 src/$PROJECT_NAME/$PROJECT_NAME.csproj
    - name: Upload Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
          name: nupkg
          path: ./src/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg
  prelease:
      needs: build
      if: github.ref == 'refs/heads/dev'
      runs-on: ubuntu-latest
      steps:
          - name: Download Artifact
            uses: actions/download-artifact@v2
            with:
                name: nupkg
                path: nupkg
          - name: Push to GitHub Feed
            run: |
                for f in ./nupkg/*.nupkg
                do
                    curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
                done
  deploy:
      needs: build
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
          - name: Download Artifact
            uses: actions/download-artifact@v2
            with:
                name: nupkg
                path: nupkg
          - name: Push to NuGet Feed
            run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
